balance_controller:
  virtual_model_controller:
    heading:
      kp: 5000
      kd: 5000
      kff: 10
    lateral:
      kp: 5000
      kd: 4000
      kff: 10
    vertical:
      kp: 10000
      kd: 5000
      kff: 100
    roll:
      kp: 10000
      kd: 1000
      kff: 0.2
    pitch:
      kp: 10000
      kd: 1000
      kff: 0.2
    yaw:
      kp: 4000
      kd: 1000
      kff: 1000
    gravity_compensation_percentage: 1.0
  contact_force_distribution:
    weights:
      force:
        heading: 1
        lateral: 1
        vertical: 1
      torque:
        roll: 10
        pitch: 10
        yaw: 5
      regularizer:
        value: 0.0001
      force_diff:
        value: 0.1
        is_use: false
    constraints:
      friction_coefficient: 0.5
      minimal_normal_force: 10
      load_factor: 1
# single_leg_controller:
#   x_direction:
#     kp: 1600
#     kd: 75
#   y_direction:
#     kp: 1600
#     kd: 75
#   z_direction:
#     kp: 1600
#     kd: 75
single_leg_controller:
  x_direction:
    kp: 700
    kd: 7
  y_direction:
    kp: 700
    kd: 7
  z_direction:
    kp: 160
    kd: 7
mpc:
  weights: [0.25, 0.25, 10, 2, 2, 50, 0., 0., 0.3, 2, 0.2, 0.1, 0]
  #roll-pitch-yaw x-y-z ang-vel vel gravity-place-holder
  #weights: [20, 20, 50.0, 10, 10, 100, 10.0, 10.0, 1.0, 1.0, 1.0, 1.0, 0]
  roll: 0.25
  pitch: 0.25
  yaw: 10
  x: 2
  y: 2
  z: 20
  roll_vel: 0.1
  pitch_vel: 0.1
  yaw_vel: 0.3
  x_vel: 0.2
  y_vel: 0.2
  z_vel: 0.2
  gravity_holder: 0.0
  steps_MPC: 8
  delta_t_MPC: 0.01
  torque_weight: 0.000001
